window:
  padding:
    x: 10
    y: 10

  opacity: 0.7

font:
  normal:
    style: Medium
    family: DroidSansM Nerd Font Mono
  size: 12.0

colors:
  primary:
    background: '#181818'
    foreground: '#eeeeee'

shell:
  program: /bin/zsh
  args:
    - --login
