window:
  padding:
    x: 10
    y: 10

  opacity: 0.1

font:
  normal:
    style: Medium
    family: DroidSansMono Nerd Font Mono
  size: 12.0

colors:
  primary:
    background: '#eeeeee'
    foreground: '#ffffff'

# shell:
  # program: /bin/fish
  # args:
    # - --login
